on:
  push:
    branches: [master]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: linux347.unoeuro.com
          username: stineplejdrup.dk
          password: ${{ secrets.ftp_password }}
          server-dir: /public_html/kea/09_cms/radio_loud/wp-content/themes/radio_loud_theme/
          exclude: .git*
            - .git*/**
            - .vscode*
